name: Ruby

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - depfu/*
      - release/*
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
