name: Ruby

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - depfu/*
      - release/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1', '3.0', '2.7', '2.6']

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
